/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElPagination: typeof import('element-plus/es')['ElPagination']
    Info: typeof import('./src/components/Info.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Player: typeof import('./src/components/player.vue')['default']
    PlayList: typeof import('./src/components/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
